# Generated by Django 5.1 on 2024-08-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appoitement_isaffected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoitement',
            name='dateAppoitement',
        ),
    ]
